#!/bin/bash
# Optional option "-a <alpino_option>"
# Option "-t maxtime" 
# Set ALPINO_HOME in hierarchy: 1) alpino_option; 2) ALPINO_HOME; 3) default (ALPINO_DEFAULT)
modname=morphosyntactic_parser_nl
#
# Find the path to this module
#
if
  [ -z ${MODROOT+x} ]
then
  # Find out path ourselves
  thisdir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"
else
  thisdir=$MODROOT/$modname
fi
scriptpath=${thisdir}/run
#
# Get "-a" or "-t" option if present.
#
opts=""
while getopts a:t: opt; do
   case $opt in
     a) ALPINO_HOME=$OPTARG
        ;;
     t) MAX_TIME=$OPTARG
        ;;
     *) echo "Unknown option." 
        exit 1
        ;;
    esac
done
#
# Set ALPINO_HOME
#
ALPINO_DEFAULT=$thisdir/Alpino
export ALPINO_HOME=${ALPINO_HOME:-$ALPINO_DEFAULT}
cd $thisdir
#
# Check for Alpino
#
if
  [ ! -x "${ALPINO_HOME}/bin/Alpino" ]
then
  echo "Cannot find Alpino" >&2
  exit 4
fi
#
# Run
# See https://stackoverflow.com/questions/3601515/how-to-check-if-a-variable-is-set-in-bash
#   for the trick to check whether MAX_TIME has been set.
#
if 
  [ -z ${MAX_TIME+x} ]
then
  python -m alpinonaf
else
  python -m alpinonaf -t $MAX_TIME
fi
 
